DROP TABLE EMPLEAT;
DROP TABLE TIPUS_PLAÇA;
DROP TABLE PLAÇA;
DROP TABLE NOMINA;
DROP TABLE OCUPA;

CREATE TABLE EMPLEAT(
    NSS NUMBER PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    LLINATGES VARCHAR2(100),
    EMAIL VARCHAR2(30),
    IBAN VARCHAR2(36) UNIQUE NOT NULL
);

CREATE TABLE TIPUS_PLAÇA(
    NOM VARCHAR2(50) PRIMARY KEY,
    FUNCIO VARCHAR2(50)
);

CREATE TABLE PLAÇA(
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    SALARI NUMBER NOT NULL,
    CODI_SUPERVISORA NUMBER REFERENCES PLAÇA (CODI),
    INFORME_SUPERVISIO VARCHAR2(50),
    NOM_TIPUS VARCHAR2(50) REFERENCES TIPUS_PLAÇA(NOM)

);

CREATE TABLE NOMINA(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    IBAN_PAGO NUMBER NOT NULL,
    IMPORTE VARCHAR2(20) NOT NULL,
    NSS_EMPLEAT NUMBER REFERENCES EMPLEAT (NSS),
    CODI_PLAÇA NUMBER REFERENCES PLAÇA (CODI) NOT NULL
);

CREATE TABLE OCUPA(
    NSS_EMPLEAT NUMBER REFERENCES EMPLEAT (NSS),
    CODI_PLAÇA NUMBER REFERENCES PLAÇA (CODI),
    PRIMARY KEY (NSS_EMPLEAT, CODI_PLAÇA),
    DATA_INICI DATE NOT NULL,
    DATA_FI DATE
);
