SELECT EXTRACT(DAY FROM SYSDATE),EXTRACT(MONTH FROM SYSDATE),EXTRACT(YEAR FROM SYSDATE) from DUAL;
SELECT ADD_MONTHS(SYSDATE, 12) FROM DUAL;
SELECT CEIL(MONTHS_BETWEEN(sysdate, DATE'2022-02-25')) from dual;