CREATE TABLE AUTOR(
    ID NUMBER GENERATED AS IDENTITY,
    nom VARCHAR2(100),
    cognoms VARCHAR2(200),
    data_naix DATE,
    nacionalitat VARCHAR2(3),
    PRIMARY KEY (ID)
);

CREATE TABLE EDITORIAL(
    ID NUMBER GENERATED AS IDENTITY,
    nom VARCHAR2(100),
    PRIMARY KEY (ID)
);

CREATE TABLE LLIBRE(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    titol VARCHAR2(50),
    ano NUMBER(4),
    exemplars NUMBER,
    ID_EDITORIAL NUMBER NOT NULL REFERENCES EDITORIAL (ID),
    ID_Sequela NUMBER REFERENCES LLIBRE (ID)
);

CREATE TABLE GENERE(
    nom VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE LLIBRE_GENERE(
    ID_LLIBRE NUMBER REFERENCES LLIBRE (ID),
    GENERE_NOM VARCHAR2(50) REFERENCES GENERE (nom),
    PRIMARY KEY (ID_LLIBRE, GENERE_NOM)
);

CREATE TABLE AUTOR_LLIBRE(
    ID_AUTOR NUMBER REFERENCES AUTOR (ID),
    ID_LLIBRE NUMBER REFERENCES LLIBRE (ID),
    PRIMARY KEY (ID_AUTOR, ID_LLIBRE)
);


