--DROPS
DROP TABLE ACCIDENT_VEHICLE;
DROP TABLE MULTA;
DROP TABLE ACCIDENT;
DROP TABLE VEHICLE;
DROP TABLE PERSONA;

CREATE TABLE PERSONA (
    DNI VARCHAR2(9) PRIMARY KEY,
    NOM VARCHAR2(50),
    LLINATGES VARCHAR2(100),
    ADRECA VARCHAR2(100),
    CODI_POSTAL VARCHAR(5) CHECK (CODI_POSTAL != '07430'),
    TELEFON NUMBER(9),
    DATA_ALTA DATE
);

CREATE TABLE VEHICLE (
    MATRICULA VARCHAR2(7) PRIMARY KEY,
    MARCA VARCHAR2(30),
    MODEL_VEHICLE VARCHAR2(30),
    CHECK (SUBSTR(MODEL_VEHICLE, 1, 4) != 'RB19'),
    DNI VARCHAR2(9) NOT NULL,
    FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE MULTA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DATA_I_HORA DATE,
    LLOC VARCHAR2(100),
    IMPORT_MULTA NUMBER(10,2) CHECK (IMPORT_MULTA >= 100.00),
    MATRICULA_VEHICLE VARCHAR2(7),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA)
);

CREATE TABLE ACCIDENT (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    LLOC VARCHAR2(100),
    DATA_I_HORA DATE
);

CREATE TABLE ACCIDENT_VEHICLE (
    MATRICULA_VEHICLE VARCHAR2(7) NOT NULL,
    CODI_ACCIDENT NUMBER NOT NULL,
    INFORME_PARTICIPACIO VARCHAR2(500),
    PRIMARY KEY (MATRICULA_VEHICLE, CODI_ACCIDENT),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA),
    FOREIGN KEY (CODI_ACCIDENT) REFERENCES ACCIDENT(CODI)
);

INSERT INTO PERSONA(DNI,NOM,LLINATGES,ADRECA,CODI_POSTAL,TELEFON,DATA_ALTA)VALUES('12345678A','Miguel','Torrents','Callecusorderaval',07430,676969348,DATE '2006-06-01');
INSERT INTO PERSONA(DNI,NOM,LLINATGES,ADRECA,CODI_POSTAL,TELEFON,DATA_ALTA)VALUES('12344321A','Alvaro','Muntaner','Callecusorderaval',07430,672305963,DATE '2007-09-26');
INSERT INTO VEHICLE VALUES('1986IGN','Renault','Model Cores','12345678A');
INSERT INTO VEHICLE VALUES('1956IFN','Mercedes','Model Zara','12345678A');
INSERT INTO VEHICLE VALUES('1926IKN','Ferrari','Model Cliot','12344321A');
INSERT INTO MULTA(DATA_I_HORA,LLOC,IMPORT_MULTA,MATRICULA_VEHICLE)VALUES(TO_DATE('2026-09-04 10:13:25', 'YYYY-MM-DD HH24:MI:SS'),'Calle macdonals','200','1986IGN');
INSERT INTO ACCIDENT(LLOC,DATA_I_HORA)VALUES('Calle burger',TO_DATE('2026-09-05 11:13:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACCIDENT_VEHICLE VALUES('1926IKN','1','Ha hecho un air dribbling pero le ha salido mal');
INSERT INTO ACCIDENT_VEHICLE VALUES('1926IKN','1','Ha sufrido el air dribbling del coche anterior y se ha quedado sin parachoques');
ALTER TABLE MULTA ADD data_pagament DATE;
ALTER TABLE ACCIDENT_VEHICLE MODIFY informe_participacio VARCHAR2(2000);
ALTER TABLE PERSONA DROP COLUMN DATA_ALTA;
UPDATE PERSONA SET NOM = 'Ronitin Suarez' WHERE DNI = '12345678A';
DELETE FROM MULTA WHERE MATRICULA_VEHICLE = '1234ABC';

